CREATE TABLE links_usage (
  linkID   INTEGER  NOT NULL,
  day DATE DEFAULT CURRENT_DATE NOT NULL,
  hit_count INT DEFAULT 1 NOT NULL,

  PRIMARY KEY (linkID, day),
  FOREIGN KEY (linkID) REFERENCES links(id)
);

ALTER TABLE links ALTER COLUMN urlID TYPE INTEGER;
